services:
  db:
    container_name: postgres3
    image: postgres:latest
    environment:
      POSTGRES_USER: bor3i
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fitness
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5335:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bor3i"]
      interval: 5s
      timeout: 5s
      retries: 5
